config/routes.rb
LongMoney::Application.routes.draw do
  resources :myitems

end

app/models/myitem.rb
class Myitem < ActiveRecord::Base
  validates :item_name, presence: true
  
  validates :sku, presence: true
  
  validates :quantity, presence: true
  
  validates :item_description, presence: true
  
  before_validation :uppercase_sku
  
  def uppercase_sku
    self.sku.upcase!
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

app/controllers/myitems_controller.rb
class MyitemsController < ApplicationController
  before_action :set_myitem, only: [:show, :edit, :update, :destroy]

  # GET /myitems
  # GET /myitems.json
  def index
    @myitems = Myitem.all
  end

  # GET /myitems/1
  # GET /myitems/1.json
  def show
  end

  # GET /myitems/new
  def new
    @myitem = Myitem.new
  end

  # GET /myitems/1/edit
  def edit
  end

  # POST /myitems
  # POST /myitems.json
  def create
    @myitem = Myitem.new(myitem_params)

    respond_to do |format|
      if @myitem.save
        format.html { redirect_to @myitem, notice: 'Myitem was successfully created.' }
        format.json { render action: 'show', status: :created, location: @myitem }
      else
        format.html { render action: 'new' }
        format.json { render json: @myitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /myitems/1
  # PATCH/PUT /myitems/1.json
  def update
    respond_to do |format|
      if @myitem.update(myitem_params)
        format.html { redirect_to @myitem, notice: 'Myitem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @myitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /myitems/1
  # DELETE /myitems/1.json
  def destroy
    @myitem.destroy
    respond_to do |format|
      format.html { redirect_to myitems_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_myitem
      @myitem = Myitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def myitem_params
      params.require(:myitem).permit(:item_name, :sku, :quantity, :item_description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/myitems_helper.rb
module MyitemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LongMoney</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/myitems/_form.html.erb
<%= form_for(@myitem) do |f| %>
  <% if @myitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@myitem.errors.count, "error") %> prohibited this myitem from being saved:</h2>

      <ul>
      <% @myitem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_name %><br>
    <%= f.text_field :item_name %>
  </div>
  <div class="field">
    <%= f.label :sku %><br>
    <%= f.text_field :sku, :id => 'txtSku', :readonly => true %>
    <button type="button" onClick="randomString();">Zzz</button>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :item_description %><br>
    <%= f.text_area :item_description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/myitems/edit.html.erb
<h1>Editing myitem</h1>

<%= render 'form' %>

<%= link_to 'Show', @myitem %> |
<%= link_to 'Back', myitems_path %>

app/views/myitems/index.html.erb
<h1>Listing myitems</h1>

<table>
  <thead>
    <tr>
      <th>Item Name</th>
      <th>Sku</th>
      <th>Quantity</th>
      <th>Item Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @myitems.each do |myitem| %>
      <tr>
        <td><%= myitem.item_name %></td>
        <td><%= myitem.sku %></td>
        <td><%= myitem.quantity %></td>
        <td><%= myitem.item_description %></td>
        <td><%= link_to 'Show', myitem %></td>
        <td><%= link_to 'Edit', edit_myitem_path(myitem) %></td>
        <td><%= link_to 'Destroy', myitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Myitem', new_myitem_path %>

app/views/myitems/new.html.erb
<h1>New myitem</h1>

<%= render 'form' %>

<%= link_to 'Back', myitems_path %>

app/views/myitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item Name:</strong>
  <%= @myitem.item_name %>
</p>

<p>
  <strong>Sku:</strong>
  <%= @myitem.sku %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @myitem.quantity %>
</p>

<p>
  <strong>Item Description:</strong>
  <%= @myitem.item_description %>
</p>

<%= link_to 'Edit', edit_myitem_path(@myitem) %> |
<%= link_to 'Back', myitems_path %>